In [36]:
#Algorithm solving Ax = b by LU분해
import numpy
n = 4
A = [[1,1,0,3],[2,1,-1,1],[3,-1,-1,2],[-1,2,3,-1]]
b1 = [8,7,14,-7]
(b,c,X,L,U) = (numpy.zeros([n,1]),numpy.zeros([n,1]),numpy.zeros([n,1]),numpy.zeros([n,n]),numpy.zeros([n,n]))
for i in range(n):
    b[i][0] = b1[i]
    L[i][i] = 1
def gap(x,y,t,s=0):
    T = int((t+1)*t*(t-1)/6)
    for i in range(T*(x+1),x+(t+1)*(y-x)+(t+1)*t*(x-y)+T*(n-4*x+3*y)):
        s += (L[x][i]*(1-T)+U[x][i]*T)*(X[i][0]*T+c[i][0]*t*(t+1)*(2-t)/2+U[i][y]*(1+t*(t+1)*(2*t-5)/6))
    return s 
for i in range(n):
    for j in range(i,n):
        U[i][j] = (A[i][j] - gap(i,j,-1))/L[i][i] #A[i][j] = gap(i,j,-1) + L[i][i]*U[i][j]
    for j in range(i+1,n):
        L[j][i] = (A[j][i] - gap(j,i,0))/U[i][i]
for i in range(n): #first Lc = b -> c
    c[i][0] = (b[i][0] - gap(i,0,1))/L[i][i]
for i in range(n): #second Ux = c -> x
    X[n-1-i][0] = (c[n-1-i][0] - gap(n-1-i,0,2))/U[n-1-i][n-1-i]
    
print(L)
print(U)
print(c)
print(X)

[[ 1.  0.  0.  0.]
 [ 2.  1.  0.  0.]
 [ 3.  4.  1.  0.]
 [-1. -3.  0.  1.]]
[[  1.   1.   0.   3.]
 [  0.  -1.  -1.  -5.]
 [  0.   0.   3.  13.]
 [  0.   0.   0. -13.]]
[[  8.]
 [ -9.]
 [ 26.]
 [-26.]]
[[ 3.]
 [-1.]
 [ 0.]
 [ 2.]]
